version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  pgadmin:
    image: dpage/pgadmin4
  discountdb:  
    image: postgres
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogAPI/Dockerfile
  cartapi:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: BasketAPI/Dockerfile
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
            - 5672:5672
            - 15672:15672
volumes:
 mongo_data:
 postgres_data:
 pgadmin_data:


